version: 2
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
  - goos: windows
    format: zip
nfpms:
- file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  homepage:  https://soh.re
  description: Designed to point out potential issues in a kubernetes node. Such as pods stuck terminating, or pending.
  maintainer: Jonathan Seth Mainguy <jon@soh.re>
  license: GPLv2
  vendor: Jmainguy
  formats:
  - deb
  - rpm
  overrides:
      deb:
        file_name_template: "{{ .ProjectName }}_{{ .Version }}-{{.Release}}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
