language: go
addons:
  apt:
    packages:
    - rpm
env:
  matrix:
  - GO111MODULE="on"
  global:
    secure: Kz3lAU0GgaeVgTRCXWfvTs2TR+uuv+02J9emZ1TKnTIBzntn2EMv/P25EzwiwEvzd/S7iAnYrSc4TqkOeLP3wPcabaYoE1HhFqGscL3tcwUIK1vxBF1Qbb6t0L71pBy277v/J/6MtpyKa6tAEEyajOMB5nbtYLYk7MlCpoV77cUAzMeIZWOSB/Xf59TN18bKI6rFr+1C/G+cUYJbFfFZqrejxLHI8ZF2jH0nMJYuYY6iRpBw6JKuFHRZZnzSe4VHJjsGy8/gu+j+vc0Ma1QGBBxIQbsdHH/PRZ6JWvL/+C528ZcrRTfXmCKZxnj1nVuRmTE70SEfniBgboH1xVfCUCcBGYBjqV8vB3nofsrVIqBPyKyq3CSV86TUlSCt5l0eOl7Cmql9LoYWpS9sGW+uHNbViLBaR8QRZZOdC558SO8ozalA1wsrCD/RMf4HpxSl0QnPu8M4oz64c9L1TgfoB8aHuOZnbvZH6yF/6wP7vDrC1K4BzUAvQN51YYLakB4fpgnIgXCVJa5jV6Z3AnZfx9UNZ4lmkoo03Zo5FBr9Zlb0QgObEZpgz4hx9EQp7RabEnGVIhxrb4aNY0smZY03gmP/fvfZrMT0zDXZsmLhUUiKXxTdIQtS/onWPyQ94LT5CniSknzMAQH7oyxQ9GO74/LqWtSepjC/yxekECmWe2I=
install: 
after_success: 
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
after_deploy:
  - ./after_deploy.sh
